### ISSUE TITLE
UI perfection

### ISSUE THREAD

**Issue by ZonaHex** [GreptimeTeam/dashboard#162]
- [x] Fix scripts modal; Flip cancel and ok color; #163 
- [x] Logs start from the latest #163 
- [x] Table tree height be 36px. #168 
- [x] Navbar select down style. #169 
- [x] Icon: Table tree icon be bigger (16px) #168 
- [x] Select dropdown, if user scrolls, it should remain the same place. #174 
- [x] Code mirror scroll style. #169 
- [x] Message: Max 3 lines. #169 
- [x] Script list select style. Margin left and right 16px. Border-radius 6px. #169 
- [x] Sider tab width 20px bigger. Change layout. #169 
- [x] Tree list be like script list. #169 
- [x] Change Readme Screenshot. #168
